# Generated by Django 3.2.5 on 2021-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ais', 'ACCOUNTING AND INFORMATION SYSTEM'), ('bn', 'BANGLA'), ('chem', 'CHEMISTRY'), ('cse', 'COMPUTER SCIENCE AND ENGINEERING'), ('dm', 'DISASTER MANAGEMENT'), ('economics', 'ECONOMICS'), ('eee', 'ELECTRICAL AND ELECTRONIC ENGINEERING'), ('en', 'ENGLISH'), ('fb', 'FINANCE AND BANKING'), ('gds', 'GENDER AND DEVELOPMENT STUDIES'), ('ges', 'GEOGRAPHY AND ENVIRONMENTAL SCIENCE'), ('hsa', 'HISTORY AND ARCHAEOLOGY'), ('p_sci', 'POLITICAL SCIENCE'), ('sociology', 'SOCIOLOGY'), ('ms', 'MANAGEMENT STUDIES'), ('marketing', 'MARKETING'), ('mcj', 'MASS COMMUNICATION AND JOURNALISM'), ('math', 'MATHEMATICS'), ('phy', 'PHYSICS'), ('p_adm', 'PUBLIC ADMINISTRATION'), ('stat', 'STATISTICS')], max_length=127, null=True),
        ),
    ]
