# Generated by Django 3.2.5 on 2021-09-10 05:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('roll', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('ais', 'ACCOUNTING AND INFORMATION SYSTEM'), ('bn', 'BANGLA'), ('chem', 'CHEMISTRY'), ('cse', 'COMPUTER SCIENCE AND ENGINEERING'), ('dm', 'DISASTER MANAGEMENT'), ('economics', 'ECONOMICS'), ('eee', 'ELECTRICAL AND ELECTRONIC ENGINEERING'), ('en', 'ENGLISH'), ('fb', 'FINANCE AND BANKING'), ('gds', 'GENDER AND DEVELOPMENT STUDIES'), ('ges', 'GEOGRAPHY AND ENVIRONMENTAL SCIENCE'), ('hsa', 'HISTORY AND ARCHAEOLOGY'), ('p_sci', 'POLITICAL SCIENCE'), ('sociology', 'SOCIOLOGY'), ('ms', 'MANAGEMENT STUDIES'), ('marketing', 'MARKETING'), ('mcj', 'MASS COMMUNICATION AND JOURNALISM'), ('math', 'MATHEMATICS'), ('phy', 'PHYSICS'), ('p_adm', 'PUBLIC ADMINISTRATION'), ('stat', 'STATISTICS')], max_length=127)),
                ('semester', models.CharField(choices=[('one', '1st'), ('two', '2nd'), ('three', '3rd'), ('four', '4th'), ('five', '5th'), ('six', '6th'), ('seven', '7th'), ('eight', '8th')], max_length=127)),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], max_length=127)),
                ('account', models.CharField(max_length=127)),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=255)),
                ('extra_transactions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('created_at', 'department'),
            },
        ),
    ]
