# Generated by Django 3.2.5 on 2021-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210910_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
